---
name: Kocom-Switch with RS485
version: 2024.08.25.09
slug: kocom_py
description: Kocom-Switch for Home Assistant
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
url: https://github.com/Hongmokee/kocom_standalone
startup: application
boot: auto
uart: true
map:
  - share:rw
options:
  share/kocom-switch/kocom.conf 설정파일: true
  share/kocom-switch/kocom.py 실행파일: true
schema:
  share/kocom-switch/kocom.conf 설정파일: bool
  share/kocom-switch/kocom.py 실행파일: bool
